### ISSUE TITLE
Publish github pages without checking the html into git

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/coq-domains#6]
It is totally crazy how I am creating merge conflicts with every commit LOL.

**Comment by jonsterling** [comment]
(See #5)

**Comment by jonsterling** [comment]
Once we set up CI, we can use this to push the docs without checking them in https://github.com/marketplace/actions/push-git-subdirectory-as-branch

**Comment by jonsterling** [comment]
Think I've got this working now.

**Comment by jonsterling** [comment]
Looks like I didn't fully get it working LOL.

**Comment by clayrat** [comment]
Ok the build itself seems to work after https://github.com/jonsterling/coq-domains/commit/f07c9b864f18e9a09fa6643e1c48439de6caacb5 but since we're running it inside docker, the publishing action (which runs directly on the host) can't find the generated files.

**Comment by clayrat** [comment]
Hm, the docker action is run with 
`-v "/home/runner/work/coq-domains/coq-domains":"/github/workspace"`, which ties the host folder to container. 
The build seems to be occuring in `/github/workspace`, so the docs should end up in `/html` on the host.
However during the publishing step we get 
`cp: no such file or directory: /home/runner/work/coq-domains/coq-domains/html/.*`

**Comment by jonsterling** [comment]
@clayrat Wow, thank you so much for figuring this out... Honestly I feel that composing CI programs is basically harder than almost any math problem LOL

**Comment by clayrat** [comment]
Yeah, this sort of rapidly accumulating accidental complexity is why DevOps positions are at the same time nicely compensated and looked down upon by developers in industry.

**Comment by jonsterling** [comment]
Yeah... when I was in industry, I had nothing but awe for my colleagues in devops...
